### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by metheos**
Updated README to reflect changes

Code redundancies and formatting cleanup

Don't re-create spectrum files if they already exist

Add some output logging for monitoring progress
e.g.
```
Converting Unable to Comply.mp3 to ogg
Generating Spectrum File for Unable to Comply.mp3
Creating EarwaxAudio.jet
Complete!
```

### CODE REVIEW

**Comment by USB3pt0** [comment]
I merged this without testing it on my end (oops!) and I ran into some problems.

I had to install a few modules for Python (numpi, scipy, and pydub) to have the script run, but when it hits spectrum generation it seems to fail to convert the oggs to wavs to generate the file.  I may be missing some prerequisite modules or applications; what is it that you use for conversion?  I may not have it installed and it may need added to the readme.  I was adding a prerequisites header for the modules but I wanted to have it working on my end before I updated it.

**Comment by metheos** [comment]
I think the only other thing I had to install was ffmpeg. Are you getting
an error message?

**Comment by USB3pt0** [comment]
I really should read more.

Anyway, at the start it says it requires avconv or ffmpeg, as well as ffprobe. It's entirely possible I just never installed ffmpeg and just grabbed the executable whenever I needed it for something.  When I get back tonight I'll run an installer for it and see if that fixes it, then patch up the readme once I get it going.

**Comment by USB3pt0** [comment]
Right so I just RD'd in since I have some downtime.  I did both a pip install ffmpeg and a manual install adding it to my PATH EV, but I still get the following errors:

```
C:\Users\Will\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

Generating Spectrum File for (Courage) The things I do for love

C:\Users\Will\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)

[WinError 2] The system cannot find the file specified

[WinError 2] The system cannot find the file specified: 'I:\\Earwax Modding/New Sounds/(Courage) The things I do for love.wav
```

**Comment by metheos** [comment]
Gotcha. Definitely seems to be having trouble finding ffmpeg.
Looks like windows. On windows I have good luck running these commands for ffmpeg support in python.
And then make sure you restart your console session of course to get the updated path.
```
pip install ffmpeg-downloader
ffdl install --add-path
```

**Comment by USB3pt0** [comment]
My main device is Windows, yeah, I didn't even think of python working on everything else. 
That did the trick on not finding ffmpeg, however now the error is this:

```
Generating Spectrum File for (Courage) The things I do for love
[Errno 2] No such file or directory: 'I:\\Earwax Modding/New Sounds/../Spectrum/(Courage) The things I do for love.jet'
```

**Comment by metheos** [comment]
Hmmm, does the spectrum folder exist?
Not sure on that one but the only time it uses the jet file path is when it
writes the json to it.

**Comment by metheos** [comment]
Just ran this on my windows machine to be sure. Only way I got that error to show up was if I was running from a directory other than the one the script was in, or the Spectrum folder hadn't been created.
But with the structure like this it works fine

image

image

We could create the folder if it's missing on like, line 96
```
if (not os.path.exists(cwd + '/../Spectrum')):
    os.mkdir(cwd + '/../Spectrum')
```

**Comment by USB3pt0** [comment]
Oh I see what I did.  I wrote this with directories premade, while in later scripts I have it make folders.  I deleted the entire Spectrum folder because I read it won't make .jets for existing ones rather than just clearing it out... maybe I should have spent more time in school on better testing methods than repeatedly trying by fire until I or someone else figures out what I did wrong.

While choosing a folder to use as a sound source is something I'm fine with holding on to a GUI for, it probably isn't a bad idea to make a Spectrum folder... I'll run it again in the right spot and see how it does.

**Comment by USB3pt0** [comment]
That did it.  When I get home I will update the readme for prereqs/windows users and mention the Anaconda distro that comes with numpy etc. as a baseline, then the ffmpeg stuff with pip.  Thanks!

**Pull request merged**
